name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        rpmName: ["test"]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: RPM Packaging
      uses: cody0704/rpm-action@v0.03
      with:
        project_name: "Test-RPM"
        packaging_path: "/services/test"
        packager: "Cody Chen"
        rpm_path: "/github/home/rpmbuild/SOURCES/"
        rpm_name: "test"
        rpm_url: "http://www.example.com"
        rpm_vendor: "test"
        rpm_apiname: "Test-RPM"
        rpm_version: "1.0.0"
        rpm_requires: "perl"
        git_enable: true
        git_token: ${{ secrets.git_token }}
    
    - name: Deploy RPM
      uses: appleboy/ssh-action@v0.0.6
      with:
        host: ${{ secrets.ssh_host }}
        username: root
        password: ${{ secrets.ssh_passwd }}
        script_stop: true
        script: |
          cd /root/cody/deploy/
          rm -rf deploy-1
          git clone https://${{ secrets.git_token }}:x-oauth-basic@github.com/${{ github.repository }} deploy-1
          cd deploy-1
          git pull
          git checkout rpm
          rpm -Uvh RPMS/x86_64/*-latest.rpm